### PR TITLE
Paged collection cache key

### LINKED ISSUE #108: Musical works paging behaving incorrectly
Eg: https://cms.prx.org/api/v1/stories/36935/musical_works.json?page=2

I would expect the `next` `_link` to be page 3, but currently it's returning page 2

### PR DESCRIPTION
**Pull request by kookster**
fix #108 

also, fix race condition in Digest::MD5 by using OpenSSL version which is thread safe

### CODE REVIEW

File: app/models/paged_collection.rb [hunk 1]
```diff
@@ -29,14 +30,12 @@ def initialize(items, request=nil, options=nil)
...
-    key_components << items.inject([0, 0]) do |keys, i|
-      keys[0] = keys[0] + i.try(:id).to_i.modulo(100)
-      keys[1] = [keys[1], i.try(:updated_at).try(:utc).to_i].max
-      keys
-    end.flatten.join("-")
-
+    item_keys = items.inject([]) do |keys, i|
+      keys << i.try(:id)
+      keys << i.try(:updated_at).try(:utc).to_i
+    end
```
Comment (chrisrhoden) [inline app/models/paged_collection.rb]: Any reason we're building this up in memory rather than using the `Digest#update` method?
