### PR TITLE
Prevent podcast distributions with no podcast

### LINKED ISSUE #209: Do not create podcast distributions without a feeder podcast
Rollback  distro create if feeder podcast create fails

### PR DESCRIPTION
**Pull request by kookster**
fixes #209 
- [x] Raise errors when podcast_url is blank when trying to set
- [x] Wrap `controller.create` in a transaction; if feeder podcast create fails, rollback the distribution create

### CODE REVIEW

**Comment by kookster** [comment]
@gcampo88 how about taking a shot at reviewing this one?

**Comment by kookster** [comment]
(ask me all the questions!)

**Comment by kookster** [comment]
actually, I think I need to add this same logic to the episode level distro - hold off reviewing pls

**Comment by gcampo88** [comment]
holding!

**Comment by kookster** [comment]
ok - I think this is complete now @gcampo88

File: test/models/distributions/podcast_distribution_test.rb [hunk 1]
```diff
@@ -7,19 +7,34 @@
...
+      distribution.account.wont_be_nil
+      distribution.save!
+      -> do
+        distribution.distribute!
+      end.must_raise(HyperResource::ServerError)
+    end
+  end
+
+  it 'throws error and rolls back if podcast on feeder fails' do
     distribution.stub(:get_account_token, 'token') do
```
Comment (gcampo88) [inline test/models/distributions/podcast_distribution_test.rb]: seems like the name of this test & the one above should be swapped?

Comment (kookster) [inline test/models/distributions/podcast_distribution_test.rb]: you're right! I changed the wrong one

File: config/initializers/faraday.rb [hunk 2]
```diff
@@ -0,0 +1,2 @@
+require 'faraday'
+Faraday.default_adapter = :excon
```
Comment (cavis) [inline config/initializers/faraday.rb]: What's this about?  Wasn't throwing errors the way your were expecting?

File: app/controllers/api/story_distributions_controller.rb [hunk 3]
```diff
@@ -13,6 +13,8 @@ class Api::StoryDistributionsController < Api::BaseController
 
   announce_actions resource: :story_resource
 
+  around_action :wrap_in_transaction, only: :create
```
Comment (cavis) [inline app/controllers/api/story_distributions_controller.rb]: Fancy!

File: config/initializers/faraday.rb (hunk 2 above)
Comment (kookster) [inline config/initializers/faraday.rb]: excon is just better! no, really it makes it easier to debug consistently since then I can set ENV['EXCON_DEBUG'] = 'true' and both hyperresource and oauth2 gems will use excon and display the full logging of the requests and responses

File: app/controllers/api/story_distributions_controller.rb (hunk 3 above)
Comment (kookster) [inline app/controllers/api/story_distributions_controller.rb]: (you know, back when I used to answer SO for fun.)
